# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HTxUMtNBcRgcrUg-XefhCFK1QcvZkfcd
"""

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Função para baixar dados das ações
def baixar_acao(ticker):
    dados = yf.download(ticker, period='1y', interval='1d')
    return dados

# Exemplo: Baixar dados da ação PETR4
dados_petroleo = baixar_acao('PETR4.SA')

# Mostrar os primeiros dados
dados_petroleo.head()
